version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: sales-review-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: sales_review
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: sales_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sales-review-network

  # 销售复盘系统
  sales-review:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sales-review-app
    ports:
      - "6092:6090"  # 前端端口映射
      - "6093:6091"  # 后端端口映射
    volumes:
      - ./backend/reports:/app/backend/reports  # 报告文件持久化
      - ./backend/uploads:/app/backend/uploads  # 上传文件持久化
      - ./conf.yaml:/app/conf.yaml  # 配置文件
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - TZ=Asia/Shanghai
      # MySQL数据库配置
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=sales_review
      - DB_CHARSET=utf8mb4
    depends_on:
      - mysql
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6091/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sales-review-network

volumes:
  mysql_data:

networks:
  sales-review-network:
    driver: bridge 